# SPDX-FileCopyrightText: 2023 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Jeremy Maceiras  <jeremy.maceiras@idiap.ch>
#
# SPDX-License-Identifier: GPL-3.0-only
planner_action_server:
  ros__parameters:
    base_frame: "world"
    tip_frame: "pen_link"
    joint_names: ["panda_joint1", "panda_joint2", "panda_joint3", "panda_joint4", "panda_joint5", "panda_joint6", "panda_joint7"]
    dof: 7
    order: 2
    rfactor: 0.0000001 # Regularization term
    init_phase_length: 500
    q_max: [10.0,10.0,10.0,10.0,10.0,10.0,10.0]
    q_min: [-10.0,-10.0,-10.0,-10.0,-10.0,-10.0,-10.0]
    dq_max: [10.0,10.0,10.0,10.0,10.0,10.0,10.0]
    dq_min: [-10.0,-10.0,-10.0,-10.0,-10.0,-10.0,-10.0]
    q0: [0.01867271925463399, 0.039659249959999386, 0.11262440969232926, -2.410346461103227, -1.8840190214282908, 2.138896759023269, 0.11947139764494366]
    orn_thresh: [0.0,0.0,0.0]
